name: model_task_unicv_create-skills-resume-dataset

on:
  workflow_dispatch:


env:
  params_cmd: "unicv create-skills-resume-dataset"
  IMAGE_TAG: ${GITHUB_REF##*/}
  IMAGE: "registry.junglejobs.ru/sever/models"
  DOCKER_CREDS_USR: ${{ secrets.DOCKER_CREDS_USR }}
  DOCKER_CREDS_PSW: ${{ secrets.DOCKER_CREDS_PSW }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: prepare
        run: |
          docker login -u "$DOCKER_CREDS_USR" -p "$DOCKER_CREDS_PSW" registry.junglejobs.ru
          docker pull $IMAGE:${GITHUB_REF##*/}

#      - name: run
#        run: |
#          docker run --rm -e VERSION=${GITHUB_REF##*/}-${BUILD_NUMBER} -e JJENV=local $IMAGE:${GITHUB_REF##*/} ${params_cmd}"
